data_dir: "data/battery_papers"
index_dir: "index/faiss"
embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
chunk_size: 900
chunk_overlap: 150
k: 4
use_openai: false
openai_model: "gpt-4o-mini"
max_context_chars: 3500